BACKPORT: PCI/pwrctrl: tc9563: Enforce I2C dependency
This driver depends on the I2C interface to configure the switch. So
enforce the dependency in Kconfig so that the I2C interface is selected
appropriately. This also avoids the build issues like the one reported by
the LKP bot:

   alpha-linux-ld: alpha-linux-ld: DWARF error: could not find abbrev number 14070
   drivers/pci/pwrctrl/pci-pwrctrl-tc9563.o: in function `tc9563_pwrctrl_remove':
>> (.text+0x4c): undefined reference to `i2c_unregister_device'
>> alpha-linux-ld: (.text+0x50): undefined reference to `i2c_unregister_device'
>> alpha-linux-ld: (.text+0x60): undefined reference to `i2c_put_adapter'
   alpha-linux-ld: (.text+0x64): undefined reference to `i2c_put_adapter'

Reported-by: kernel test robot <lkp@intel.com>
Closes: https://lore.kernel.org/oe-kbuild-all/202511200555.M4TX84jK-lkp@intel.com
Signed-off-by: Manivannan Sadhasivam <mani@kernel.org>
Acked-by: Bartosz Golaszewski <bartosz.golaszewski@linaro.org>